### ISSUE TITLE
sparse matrix input 

### ISSUE THREAD

**Issue by dselivanov** [evanwang1990/FMwR#1]
Hi. Thanks for your work, looks like amazing package (but documentation little bit sparse).
Is it possible to allow sparse matrix input to `fm`, not formula?

I also looked to `fastFM` library to make R interface, but don't have time for that. However I noticed that you implemented everything from scratch here. Any reasons to not use fastFM (I realize that here you implemented more optimizers and openmp support, but mb something else)? 

Will be happy to contribute to development.

**Comment by evanwang1990** [comment]
Hi dselivanov, thanks for your feedback.  I'm sorry for my laziness and poor English, the documentation is not finished yet... 

I will contruct the fm.matrix object  from dense matrix, sparse matrix or formula, which is the only input form for `fm`. The only reason to not use fastFm is that I think it is much more easier to process data with `data.table` in R than `Pandas` in python, haha...

**Comment by dselivanov** [comment]
Agree about `data.table` :-) But I meant wrap [fastFM-core](https://github.com/ibayer/fastFM-core) underlying `C` library. Before I found this repo I thought create R/Rcpp interface to fastFM-core.

**Comment by evanwang1990** [comment]
I have created a function `fm.matrix`, which accepts dense matrix, sparse matrix or data.frame as input

**Comment by dselivanov** [comment]
thanks! will test this weekend.

**Comment by evanwang1990** [comment]
there are two simple examples in fm_train.Rd

**Comment by dselivanov** [comment]
Sparse matrices works fine, so I'm closing this. Thank you for fast implementation.
